services:
  php:
    image: php:8.2-apache
    container_name: php82
    ports:
      - 8000:80 
    build:
      context: ./tools
      dockerfile: DockerFile
    volumes:
      - .:/var/www/html
    depends_on:
      - database 

  database:
    image: mysql:8.0
    container_name: mysql8
  
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: log2
      MYSQL_USER: uzh 
      MYSQL_PASSWORD: test
    ports:
      - 3307:3306

  phpma:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin 
    environment:
      PMA_ARBRITRARY: 1
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: test
    ports:
      - 8899:80
       